### ISSUE TITLE
License incompatible with Github TOS

### ISSUE THREAD

**Issue by Kurty00** [talhanation/smallships#29]
Unfortunately your license violates GitHubs Terms of Service as it prevents other people from creating forks. (See [GitHub TOS - D5](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#5-license-grant-to-other-users))

> Any User-Generated Content you post publicly, including issues, comments, and contributions to other Users' repositories, may be viewed by others. By setting your repositories to be viewed publicly, you agree to allow others to view and "fork" your repositories (this means that others may make their own copies of Content from your repositories in repositories they control).
> 
> If you set your pages and repositories to be viewed publicly, you grant each User of GitHub a nonexclusive, worldwide license to use, display, and perform Your Content through the GitHub Service and to reproduce Your Content solely on GitHub as permitted through GitHub's functionality (for example, through forking). 

I therfore highly recommend switching to an open-source license.
Should you require assistance picking a license, I would recommend [choosealicense.com](https://choosealicense.com/), as well as the following two Stackexchange answers: 
- [1](https://opensource.stackexchange.com/questions/9805/can-i-license-my-project-with-an-open-source-license-but-disallow-commercial-use)
- [2](https://opensource.stackexchange.com/questions/21/whats-the-difference-between-permissive-and-copyleft-licenses/42#42)

Feel free to contact me if you should require further assistance.

**Comment by metroite** [comment]
You are misinformed. Take a look here:
https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license

Please don't give legal advice without knowledge.
