### ISSUE TITLE
Entity ticking crashes server on MC 1.20.1 and Small Ships 2.0.0-b1.4

### ISSUE THREAD

**Issue by XavierBit** [talhanation/smallships#33]
Minecraft version: 1.20.1
Mod version: Small Ships 2.0.0-b1.4
Loader: Fabric
Environment: SMP

Hi!
We are using the mod which was included in Fantasy MC Fabric and we have a problem crashing the server when loading a ship.

I have seen some updates for 1.20.1 and Small Ships but I'm unsure which one would resolve this problem and if those updates would be solely server side or if clients would need to update as well.

See our server crash log: https://mclo.gs/zo9CImZ

Thank you for your feedback!

**Comment by metroite** [comment]
Please use our bug tracker on Discord!
